server.port: 9000

logging:
  level.org.springframework:
    security: TRACE
    web.client: DEBUG

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          auth-client:
            registration:
              client-id: "auth-client-id"
              client-secret: "{bcrypt}$2a$10$jdJGhzsiIqYFpjJiYWMl/eKDOd8vdyQis2aynmFN0dgJ53XvpzzwC"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://auth-client.poc.com:8000/login/oauth2/code/auth-client-poc"
              post-logout-redirect-uris:
                - "http://auth-client.poc.com:8000/logout"
              scopes:
                - "openid"
            require-authorization-consent: true